version: '3.8'

services:
  frontend:
    build:
      context: ./forge-app
      dockerfile: Dockerfile.frontend
    ports:
      - '5173:5173'
    volumes:
      - ./forge-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./forge-back
      dockerfile: Dockerfile.backend
    ports:
      - '8000:8000'
    volumes:
      - ./forge-back:/app
    environment:
      - PYTHONUNBUFFERED=1
      - CORS_ORIGINS=http://localhost:5173
