data:
  raw_dir: 'data/raw'
  processed_dir: 'data/processed'
  models_dir: 'data/models'
  image_size: 512
  batch_size: 4

model:
  base_model: 'runwayml/stable-diffusion-v1-5'
  device: 'cuda'
  precision: 'fp16'
  lora:
    rank: 4
    alpha: 32

training:
  learning_rate: 1e-4
  num_epochs: 100
  save_steps: 500
  eval_steps: 100
  gradient_accumulation_steps: 4
