data:
  raw_dir: 'data/raw'
  processed_dir: 'data/processed'
  image_size: 512
  batch_size: 4
  num_workers: 2

model:
  base_model: 'runwayml/stable-diffusion-v1-5'
  device: 'cuda'
  precision: 'fp16'
  lora:
    rank: 4
    alpha: 32

training:
  output_dir: 'data/models'
  learning_rate: 1e-4
  num_epochs: 100
  batch_size: 4
  save_steps: 500
  eval_steps: 100
  gradient_accumulation_steps: 4
  num_workers: 2

# ... previous config settings ...

inference:
  checkpoint_path: 'data/models/latest' # Path to fine-tuned model
  enable_xformers: true # Enable memory efficient attention
  output_dir: 'data/generated'
  batch_defaults:
    num_images: 1
    guidance_scale: 7.5
    num_inference_steps: 50
  prompt_templates:
    - 'high quality NFT art piece, {prompt}, digital art, trending on artstation'
    - 'professional NFT artwork of {prompt}, detailed, vibrant colors'
  style_modifiers:
    - 'digital art'
    - 'trending on artstation'
    - 'detailed'
    - 'vibrant colors'
    - 'professional'
    - 'collectible'
